esphome:
  name: esp-ring
  friendly_name: ESP Ring
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: esphome.ring
    version: "1.0"

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:

ota:

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://mwood77/home-assistant/esp-home/esp-ring.yaml@main

wifi:
  ssid: !secret wifi_ssid 
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esphome-ring"
    password: "123456"

captive_portal:

switch:
  - platform: gpio
    id: relay
    name: "Doorbell Relay"
    icon: "mdi:doorbell"
    pin: GPIO14
    on_turn_on:
    - delay: 1100ms
    - switch.turn_off: relay
    
